language: c
os: linux
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
branches:
  only:
    - master
    - debian-unstable
    - coverity_scan
before_install:
  - wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz -O libsodium.tar.gz && tar xzf libsodium.tar.gz && cd libsodium-* && ./autogen.sh && ./configure --prefix=$HOME/libsodium && make check && make install
script:
  - export PATH=$PATH:$HOME/libsodium
  - ./autogen.sh && ./configure --prefix=$HOME/build_mlvpn && make V=1 && make install
cache:
  directories:
  - $HOME/libsodium
env:
  global:
   - secure: "Noxed1PEztsf6kRoFy17lmrsDW75SM6NK3lkHQ8yeyYvDtF3vzHXJ4TAgpcDA1RLuzOLvSjnkuucjWb8YLoisW3qs31h26qeZzN+PbeaMYFmtmkZJOiPorbtHYA47pB2xfdujoi1kSne/fHFXY0Jybj2DcUbYUS+9plnZ+4pV2w="
addons:
  apt:
    packages:
    - libev-dev
    - automake
    - autoconf
    - libtool
    - pkg-config
  coverity_scan:
    project:
      name: "zehome/MLVPN"
      description: "Build submitted via Travis CI"
    notification_email: ed@zehome.com
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: "make"
    branch_pattern: coverity_scan
